Update dependencies
cardstack/tokenbridge-contracts pull request #12
Opened 2022-03-23 13:28 UTC by jurgenwerk

Updated a couple of dependencies where `yarn audit` reported vulnerabilities.

2022-03-23 13:41 UTC, jurgenwerk commented
Looking into the lint issue...

2022-03-24 11:16 UTC, jurgenwerk commented on .solhint.json
> +    "reason-string": "off"
https://protofire.github.io/solhint/docs/rules/best-practises/reason-string.html

There's quite a lot of contracts where the reason is not provided I opted into turning this warning off

2022-03-28 01:36 UTC, alex-cardstack approved these changes
Looks good, thanks!

2022-03-28 01:40 UTC, alex-cardstack requested changes

2022-03-28 01:40 UTC, alex-cardstack commented on contracts/upgradeable_contracts/BasicHomeBridge.sol
> +        uint256 numberOfCollectedSignatures
Events are processed externally, we should not change the name here as it will result in inconsistent history on-chain

2022-03-28 01:40 UTC, alex-cardstack commented on contracts/upgradeable_contracts/arbitrary_message/BasicHomeAMB.sol
> +        uint256 numberOfCollectedSignatures
Events are processed externally, we should not change the name here as it will result in inconsistent history on-chain

2022-03-28 01:40 UTC, alex-cardstack commented on contracts/upgradeable_contracts/erc721_to_erc721/ERC721Proxy.sol
> +    constructor(string memory _name, string memory _symbol) public {
Hmm, I think we should be storing the chainId instead of removing the param but I might have to review a bit more why it's not used right now

2022-03-28 01:40 UTC, alex-cardstack commented on contracts/upgradeable_contracts/erc721_to_erc721/mediator/HomeNftMediator.sol
> +        homeTokenAddress = new ERC721Proxy(name, symbol);
I think we should be passing this in and using it in the contract but need to confirm for sure

2022-03-28 08:49 UTC, jurgenwerk commented on contracts/upgradeable_contracts/arbitrary_message/BasicHomeAMB.sol
> +        uint256 numberOfCollectedSignatures
I see! Fixed in https://github.com/cardstack/tokenbridge-contracts/pull/12/commits/f739bb854afc2852a9f949d05b8f19bfb3e77f4c

2022-03-28 08:58 UTC, jurgenwerk commented on contracts/upgradeable_contracts/erc721_to_erc721/ERC721Proxy.sol
> +    constructor(string memory _name, string memory _symbol) public {
Ok, so `chainId = _chainId;`? Why do you think we need it - what would it be used for?

2022-03-28 14:03 UTC, alex-cardstack commented on contracts/upgradeable_contracts/erc721_to_erc721/ERC721Proxy.sol
> +    constructor(string memory _name, string memory _symbol) public {
@jurgenwerk this is a real bug and it's great that we've caught it before we deployed any bridged NFTs!

I actually only realised this when looking at the chainId stuff as part of CS-2862 - I will address as part of that issue

2022-03-28 16:42 UTC, alex-cardstack commented on contracts/upgradeable_contracts/erc721_to_erc721/ERC721Proxy.sol
> +    constructor(string memory _name, string memory _symbol) public {
@jurgenwerk this is part of the code we're going to delete - so fine to roll it back for now and I'll address it as part of chainId work

2022-03-29 08:03 UTC, jurgenwerk commented
@alex-cardstack thanks for clarification, I removed the commit where `_chainId` was removed, and added a temporary linter ignore line until the chain id validation work is done.

2022-03-29 15:27 UTC, alex-cardstack approved these changes

2022-03-29 15:27 UTC, merged